list_1=[2, 4, 12, 23, 6]
print(list_1)
# print(list_1.pop())
# print(list_1)
# print(list_1.pop(1))
# print(list_1)
# a = list_1.pop(2)
# print(list_1)
# print(a)
# print(list_1)
t = ()
print(type(t))